### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by onlyjob** [Zaryob/iksemel#2]
Thank you for maintaining the most active fork/continuation of _iksemel_.

Could you consider to tag releases please?

See also https://github.com/meduketto/iksemel/issues/53

**Comment by Zaryob** [comment]
👍🏻

**Comment by Zaryob** [comment]
Sorry for late come back. I will actively maintain this code. And also I will publish releases as regular as possible

**Comment by Zaryob** [comment]
old release's archives stored in here. 

https://github.com/Zaryob/iksemel/releases/tag/iksemel-old
